title: "«Эфир»"
description: "24/7"
baseurl: ""  # Если сайт будет на поддомене, укажите базовый URL здесь
url: "http://air.indexmod.xyz"  # URL для тестирования на поддомене

# Папка для хранения 24-часовых страниц
collections:
  hours:
    output: true
    permalink: /:collection/:name  # URL-структура для каждой страницы часа

# Настройка генерации страниц и их взаимодействия
defaults:
  - scope:
      path: "_hours"
      type: "hours"
    values:
      layout: hour
      weekdays: "1234567"  # Показ ежедневно
      duration: 3600  # 1 час в секундах

# Подключение папок с макетами, стилями и инклюдами
include:
  - "_layouts"
  - "assets"

# Локальная конфигурация (если нужно)
timezone: "Europe/Moscow"  # Укажите ваш часовой пояс

# Дополнительные настройки
markdown: kramdown
kramdown:
  input: GFM

supabase_url: "https://ysoyybfvdpfcbjvbnocc.supabase.co"
supabase_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlzb3l5YmZ2ZHBmY2JqdmJub2NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIzODQ3MzYsImV4cCI6MjA0Nzk2MDczNn0.2lVwjfYdRqKNz1tfuIA3hcRTyml3OIohKuC6AL677MM"
